### ISSUE TITLE
Presubmits are failing; workflow names are too long

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#1012]
Here's a failing presubmit
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_manifests/1011/kubeflow-manifests-presubmit/1239560778768453632/

The workflow fails to be submitted

```

INFO|2020-03-16T14:35:59|/src/kubeflow/testing/py/kubeflow/testing/util.py|72| INFO|2020-03-16T14:35:59|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|92| Importing path kubeflow.kfctl.testing.ci.kfctl_e2e_workflow
INFO|2020-03-16T14:36:00|/src/kubeflow/testing/py/kubeflow/testing/util.py|72| INFO|2020-03-16T14:36:00|/src/kubeflow/testing/py/kubeflow/testing/e2e_tool.py|32| Dumping workflow to /tmp/tmpFiPgPg
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 532, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 522, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 388, in run
    body=wf_result)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 178, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 277, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 364, in request
    body=body)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 16 Mar 2020 14:36:01 GMT', 'Audit-Id': '191922cd-8da7-4479-937d-fa6487aa1eea', 'Content-Length': '676', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Workflow.argoproj.io \"kubeflow-manifests-presubmit-kfctl-go-iap-1011-915cfed-3632-0564\" is invalid: metadata.labels: Invalid value: \"kubeflow-manifests-presubmit-kfctl-go-iap-1011-915cfed-3632-0564\": must be no more than 63 characters","reason":"Invalid","details":{"name":"kubeflow-manifests-presubmit-kfctl-go-iap-1011-915cfed-3632-0564","group":"argoproj.io","kind":"Workflow","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"kubeflow-manifests-presubmit-kfctl-go-iap-1011-915cfed-3632-0564\": must be no more than 63 characters","field":"metadata.labels"}]},"code":422}
```

Not sure what changed.

**Comment by jlewi** [comment]
There are no results showing up in the testgrid
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-manifests-presubmit

Link to prow jobs:
https://prow.k8s.io/?repo=kubeflow%2Fmanifests&type=presubmit

**Comment by jlewi** [comment]
Successful presubmit from this morning
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_manifests/558/kubeflow-manifests-presubmit/1239560906409512960/

Workflows are 
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-manifests-presubmit-unit-558-eacc5e3-2960-14f8?tab=workflow
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-manifests-presubmit-kfctl-go-iap-558-eacc5e3-2960-d3b6?tab=workflow

So it looks like what happened is that the PR numbers now started being larger than 1000 and that increased the length of the workflow names by 1 which pushed it over the limit.
