### ISSUE TITLE
Test make generate failure 

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#1077]
Seem test are refactored recently and I'd like to verify if everything is still working as normal? 
Do we change the way to generate tests and run tests? Seems all past test have been moved to `legacy` folder now. Should we do the migration first? 

```
 make generate-changed-only
../hack/generate_tests.py || echo done
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|101| Removing unexpected test: /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/jupyter/jupyter-web-app/base_v3/kustomize_test.go
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|119| Removing directory: /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/jupyter/jupyter-web-app/base_v3
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|119| Removing directory: /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/jupyter/jupyter-web-app/overlays/application
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|185| Regenerating test /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/gpu-driver/kustomize_test.go for /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/legacy_kustomizations/gpu-driver
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|44| Removing directory /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/gpu-driver/test_data/expected
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|47| Creating directory /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/gpu-driver/test_data/expected
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|135| Writing file: /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/gpu-driver/kustomize_test.go
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|185| Regenerating test /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/profiles/kustomize_test.go for /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/legacy_kustomizations/profiles
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|44| Removing directory /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/profiles/test_data/expected
INFO|2020-04-04T17:43:37|../hack/generate_tests.py|47| Creating directory /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/profiles/test_data/expected
Error: merging from generator &{0xc00003cba0 0xc000010a50 {map[] map[] false} {{ profiles-parameters merge {[] [] [params_0.env] }}}}: cannot find resource with id ~G_v1_ConfigMap|~X|profiles-profiles-parameters to replace
Traceback (most recent call last):
  File "../hack/generate_tests.py", line 188, in <module>
    run_kustomize_build(repo_root, full_dir)
  File "../hack/generate_tests.py", line 52, in run_kustomize_build
    package_dir))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['kustomize', 'build', '--load_restrictor', 'none', '-o', u'/Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/profiles/test_data/expected']' returned non-zero exit status 1
done
go fmt ./...
tests/legacy_kustomizations/gpu-driver/kustomize_test.go

```

@jlewi @krishnadurai

**Comment by jlewi** [comment]
@Jeffwan It looks like `kustomize build` is segfaulting on your machine. What version of kustomize are you running?

To debug you could run the command that is being executed in a subprocess to get more info on why it failed

```
subprocess.CalledProcessError: Command '['kustomize', 'build', '--load_restrictor', 'none', '-o', u'/Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/profiles/test_data/expected']' returned non-zero exit status 1
```

**Comment by Jeffwan** [comment]
I am using v3.5.4 now. 

```
$ kustomize build --load_restrictor none -o /Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests/tests/legacy_kustomizations/cert-manager/test_data/expected

Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests'
```

It's trying to build this folder but no `kustomization.yaml` found.

**Comment by jlewi** [comment]
@Jeffwan because test_data/expected will contain the kustomization.yaml from which expected output is to be generated. See #1066. Currently kustomization.yamls are auto-generated by kfctl. So theren't were any kustomization.yamls in kubeflow/manifests that were representative of the transformations that were actually being applied. So in tests/legacy_kustomizations we checked in kustomization.yamls based on the ones kfctl generates. These are used as test cases. From these kustomiztaion.yamls we generate the expected output.

It should be using 
https://github.com/kubeflow/manifests/tree/master/tests/legacy_kustomizations/cert-manager

Which has a kustomization.yaml.

It looks like the wrong directory is being passed

```
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/shjiaxin/go-workspace/src/github.com/kubeflow/manifests/tests'
```

Are you running `make tests` from 

```
${GITHUB_MANIFESTS}/tests
```

**Comment by Jeffwan** [comment]
@jlewi 

`make test` actually works for me. `make generate-changed-only` doesn't.
I ran `make generate-changed-only` from `${GITHUB_MANIFESTS}/tests`.  

> It looks like the wrong directory is being passed

`make generate-changed-only` will look for `kustomization.yaml` in the current folder which is `${GITHUB_MANIFESTS}/tests`. Apparently, it doesn't have kustomization.yaml. 

Do we still need to `make generate-changed-only` before `make test`?

**Comment by Jeffwan** [comment]
Never mind, I change kustomize from v3.5.3 to v3.2.3 and it's working now.
