### ISSUE TITLE
AWS EKS fluentd-cloud-watch pod missing - can't get worker node group logging

### ISSUE THREAD

**Issue by dilzeem** [kubeflow/manifests#1082]
Trying to follow along here to get the worker node logs: 
https://www.kubeflow.org/docs/aws/logging/

Add the fluentd-cloud-watch to `kfctl_aws_cognito.v1.0.0.yaml` but does not get deployed. 

The logs from the control logging plane are visible. 

Looking at all the pods in all namespaces I can't seem to find fluentd at all. Looking at the `kustomize` and `aws_config` directory there doesn't seem to be any fluentd yaml files generated.

**Comment by Jeffwan** [comment]
@dilzeem 

Sorry about that, we recently have some refactoring and this has been removed.  I will try to add to v1.0.2 version. 
User still need to update param.env here and then `kubectl apply -k fluentd-cloud-watch/base`

**Comment by dilzeem** [comment]
Sure i figured as much. 

Thanks for the quick response :)

**Comment by dilzeem** [comment]
Not sure if it is how I configured. But the fluentd pods are up, but some issue with permissions. 

The log files:
```
2020-05-12 12:47:54 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
#<Thread:0x00007f6be196a768@/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:263 run> terminated with exception (report_on_exception is true):
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:34:in `rescue in start_pod_watch': Exception encountered fetching metadata from Kubernetes API endpoint: pods is forbidden: User "system:serviceaccount:kubeflow:fluentd" cannot list resource "pods" in API group "" at the cluster scope ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:kubeflow:fluentd\" cannot list resource \"pods\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"pods"},"code":403} (Fluent::ConfigError)
)
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:27:in `start_pod_watch'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:263:in `block in configure'
/fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:130:in `rescue in handle_exception': pods is forbidden: User "system:serviceaccount:kubeflow:fluentd" cannot list resource "pods" in API group "" at the cluster scope (Kubeclient::HttpError)
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:120:in `handle_exception'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:330:in `get_entities'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:212:in `block (2 levels) in define_entity_methods'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:101:in `method_missing'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:28:in `start_pod_watch'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:263:in `block in configure'
/fluentd/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 403 Forbidden (RestClient::Forbidden)
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
        from /usr/local/lib/ruby/2.6.0/net/http.rb:920:in `start'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/resource.rb:51:in `get'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:332:in `block in get_entities'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:121:in `handle_exception'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:330:in `get_entities'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:212:in `block (2 levels) in define_entity_methods'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/kubeclient-4.5.0/lib/kubeclient/common.rb:101:in `method_missing'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:28:in `start_pod_watch'
        from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:263:in `block in configure'
2020-05-12 12:47:54 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Exception encountered fetching metadata from Kubernetes API endpoint: pods is forbidden: User \"system:serviceaccount:kubeflow:fluentd\" cannot list resource \"pods\" in API group \"\" at the cluster scope ({\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods is forbidden: User \\\"system:serviceaccount:kubeflow:fluentd\\\" cannot list resource \\\"pods\\\" in API group \\\"\\\" at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"pods\"},\"code\":403}\n)"
```
