### ISSUE TITLE
setup kubeflow issue with istio manifest with v1.1 release branch

### ISSUE THREAD

**Issue by Utkagr** [kubeflow/manifests#1565]
Hi, 

I'm using latest kfctl release (https://github.com/kubeflow/kfctl/releases/tag/v1.1.0) and master's istio manifest https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.yaml on an on-prem kubernetes cluster.
At the end of the installation, I'm getting the following error. All the pods are in running state, though. Can anyone please explain what's happening? Thanks already!

```
...
...
application.app.k8s.io/spark-operator created
INFO[0300] Successfully applied application spark-operator  filename="kustomize/kustomize.go:209"
INFO[0300] Deploying application metadata                filename="kustomize/kustomize.go:172"
ERRO[0300] error evaluating kustomization manifest for metadata Error env source files: [secrets.env]: evalsymlink failure on '/home/utkarsh.agrawal/git/genie/kubeflow/ku
stomize/metadata/secrets.env' : lstat /home/utkarsh.agrawal/git/genie/kubeflow/kustomize/metadata/secrets.env: no such file or directory  filename="kustomize/kustomize.go
:175"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manif
est for metadata Error env source files: [secrets.env]: evalsymlink failure on '/home/utkarsh.agrawal/git/genie/kubeflow/kustomize/metadata/secrets.env' : lstat /home/utkarsh.agrawal/git/genie/kubeflow/kustomize/metadata/secrets.env: no such file or directory
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for
 metadata Error env source files: [secrets.env]: evalsymlink failure on '/home/utkarsh.agrawal/git/genie/kubeflow/kustomize/metadata/secrets.env' : lstat /home/ut
karsh.agrawal/git/genie/kubeflow/kustomize/metadata/secrets.env: no such file or directory
```

**Comment by Utkagr** [comment]
Also, I can't see kfserving pods which means that the complete installation failed with the error mentioned above while the pods that are running were installed correctly.

**Comment by jzhoucliqr** [comment]
any reason you choose the manifest from master branch? maybe you should try from the v1.1 release branch:  https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml

**Comment by Utkagr** [comment]
@jzhoucliqr I tried using the manifest from v1.1 release branch but facing this issue.
```
failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for application Error accumulating resources: accumulating resources from '../application-crds/base': evalsymlink failure on '/home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds/base' : lstat /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds: no such file or directory
```
I remove caches and kustomize directories before applying manifests. I do `rm -r ${KF_DIR}`, remove all the namespaces and delete leftover resources described in this issue as well. https://github.com/kubeflow/kubeflow/issues/3767

**Comment by Utkagr** [comment]
Here're the complete logs
```
INFO[0000] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml to /tmp/807156115/tmp.yaml  filename="utils/k8utils.go:172"
INFO[0003] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml to /tmp/186026966/tmp_app.yaml  filename="loaders/loaders.go:71"
INFO[0005] App directory /home/utkarsh.agrawal/git/genie/kubeflow/deployment already exists  filename="coordinator/coordinator.go:270"
INFO[0005] Writing KfDef to kfctl_k8s_istio.v1.1.0.yaml  filename="coordinator/coordinator.go:273"
INFO[0005] No name specified in KfDef.Metadata.Name; defaulting to deployment based on location of config file: /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kfctl_k8s_istio.v1.1.0.yaml.  filename="coordinator/coordinator.go:202"
INFO[0005]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0005] Creating directory /home/utkarsh.agrawal/git/genie/kubeflow/deployment/.cache  filename="kfconfig/types.go:445"
INFO[0005] Fetching https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz to /home/utkarsh.agrawal/git/genie/kubeflow/deployment/.cache/manifests  filename="kfconfig/types.go:493"
INFO[0013] updating localPath to /home/utkarsh.agrawal/git/genie/kubeflow/deployment/.cache/manifests/manifests-1.1-branch  filename="kfconfig/types.go:540"
INFO[0013] Fetch succeeded; LocalPath /home/utkarsh.agrawal/git/genie/kubeflow/deployment/.cache/manifests/manifests-1.1-branch  filename="kfconfig/types.go:561"
INFO[0013] Processing application: namespaces            filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/namespaces/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/namespaces/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: application           filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: istio-stack           filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/istio-stack/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/istio-stack/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: cluster-local-gateway  filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/cluster-local-gateway/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/cluster-local-gateway/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: istio                 filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/istio/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/istio/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: cert-manager-crds     filename="kustomize/kustomize.go:408"
INFO[0000] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml to /tmp/807156115/tmp.yaml  filename="utils/k8utils.go:172"
INFO[0003] Downloading https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml to /tmp/186026966/tmp_app.yaml  filename="loaders/loaders.go:71"
INFO[0005] App directory /home/utkarsh.agrawal/git/genie/kubeflow/deployment already exists  filename="coordinator/coordinator.go:270"
INFO[0005] Writing KfDef to kfctl_k8s_istio.v1.1.0.yaml  filename="coordinator/coordinator.go:273"
INFO[0005] No name specified in KfDef.Metadata.Name; defaulting to deployment based on location of config file: /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kfctl_k8s_istio.v1.1.0.yaml.  filename="coordinator/coordinator.go:202"
INFO[0005]
****************************************************************
Notice anonymous usage reporting enabled using spartakus
To disable it
If you have already deployed it run the following commands:
  cd $(pwd)
  kubectl -n ${K8S_NAMESPACE} delete deploy -l app=spartakus

For more info: https://www.kubeflow.org/docs/other-guides/usage-reporting/
****************************************************************
  filename="coordinator/coordinator.go:120"
INFO[0005] Creating directory /home/utkarsh.agrawal/git/genie/kubeflow/deployment/.cache  filename="kfconfig/types.go:445"
INFO[0005] Fetching https://github.com/kubeflow/manifests/archive/v1.1-branch.tar.gz to /home/utkarsh.agrawal/git/genie/kubeflow/deployment/.cache/manifests  filename="kfconfig/types.go:493"
INFO[0013] updating localPath to /home/utkarsh.agrawal/git/genie/kubeflow/deployment/.cache/manifests/manifests-1.1-branch  filename="kfconfig/types.go:540"
INFO[0013] Fetch succeeded; LocalPath /home/utkarsh.agrawal/git/genie/kubeflow/deployment/.cache/manifests/manifests-1.1-branch  filename="kfconfig/types.go:561"
INFO[0013] Processing application: namespaces            filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/namespaces/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/namespaces/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: application           filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: istio-stack           filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/istio-stack/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/istio-stack/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: cluster-local-gateway  filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/cluster-local-gateway/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/cluster-local-gateway/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: istio                 filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/istio/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/istio/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: cert-manager-crds     filename="kustomize/kustomize.go:408"
WARN[0013] Cannot get kustomization from /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/cert-manager-crds/base: error open /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/cert-manager-crds/base/kustomization.yaml: no such file or directory  filename="kustomize/kustomize.go:524"
INFO[0013] Processing application: cert-manager-kube-system-resources  filename="kustomize/kustomize.go:408"
Warning:  apply should be used on resource created by either  create --save-config or  apply
namespace/kubeflow configured
INFO[0013] Successfully applied application namespaces   filename="kustomize/kustomize.go:209"
INFO[0013] Deploying application application             filename="kustomize/kustomize.go:172"
2020/09/23 12:22:25 absolute path error in '/home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds/base' : evalsymlink failure on '/home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds/base' : lstat /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds: no such file or directory
ERRO[0013] error evaluating kustomization manifest for application Error accumulating resources: accumulating resources from '../application-crds/base': evalsymlink failure on '/home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds/base' : lstat /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds: no such file or directory  filename="kustomize/kustomize.go:175"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for application Error accumulating resources: accumulating resources from '../application-crds/base': evalsymlink failure on '/home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds/base' : lstat /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds: no such file or directory
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
  -f, --file string   Static config file to use. Can be either a local path:
                                export CONFIG=./kfctl_gcp_iap.yaml
                        or a URL:
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                        kfctl apply -V --file=${CONFIG}
  -h, --help          help for apply
  -V, --verbose       verbose output default is false

failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for application Error accumulating resources: accumulating resources from '../application-crds/base': evalsymlink failure on '/home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds/base' : lstat /home/utkarsh.agrawal/git/genie/kubeflow/deployment/kustomize/application-crds: no such file or directory
```

**Comment by jzhoucliqr** [comment]
can u please double check your kfctl version?  

$ kfctl version

**Comment by Utkagr** [comment]
@jzhoucliqr thanks for the hint! Somehow, I was using v1.0.2. I fixed that and it worked but I ran into this https://github.com/kubeflow/manifests/issues/959
I'm setting it up on on-prem 4 node k8s cluster so I'm a bit skeptical about editing kube-apiserver since I'm not sure about it's impact on the other services. 
Here's the output for `kubectl get events -n kubeflow`

```
LAST SEEN   TYPE      REASON        OBJECT                                           MESSAGE
7m48s       Warning   FailedMount   pod/cache-deployer-deployment-6f85d95759-qkdb9   MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
2m3s        Warning   FailedMount   pod/cache-deployer-deployment-6f85d95759-qkdb9   Unable to mount volumes for pod "cache-deployer-deployment-6f85d95759-qkdb9_kubeflow(66f617d8-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"cache-deployer-deployment-6f85d95759-qkdb9". list of unmounted volumes=[istio-token]. list of unattached volumes=[kubeflow-pipelines-cache-deployer-sa-token-sqgzn istio-envoy sds-uds-path istio-token]
7m49s       Warning   FailedMount   pod/cache-server-84c4b57795-2bkfk                MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
2m57s       Warning   FailedMount   pod/cache-server-84c4b57795-2bkfk                Unable to mount volumes for pod "cache-server-84c4b57795-2bkfk_kubeflow(66facec1-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"cache-server-84c4b57795-2bkfk". list of unmounted volumes=[webhook-tls-certs istio-token]. list of unattached volumes=[webhook-tls-certs kubeflow-pipelines-cache-token-frht8 istio-envoy sds-uds-path istio-token]
23m         Warning   Unhealthy     pod/katib-db-manager-6dbdf55f97-jnhhb            Readiness probe failed: timeout: failed to connect service ":6789" within 1s
3m16s       Warning   BackOff       pod/katib-db-manager-6dbdf55f97-jnhhb            Back-off restarting failed container
2m49s       Warning   Unhealthy     pod/katib-mysql-cfdbbfb65-vsmx4                  Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
7m44s       Warning   FailedMount   pod/metadata-writer-5f6d6c7bfd-rr5dg                   MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
3m6s        Warning   FailedMount   pod/metadata-writer-5f6d6c7bfd-rr5dg                   Unable to mount volumes for pod "metadata-writer-5f6d6c7bfd-rr5dg_kubeflow(68c5c5dd-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"metadata-writer-5f6d6c7bfd-rr5dg". list of unmounted volumes=[istio-token]. list of unattached volumes=[kubeflow-pipelines-metadata-writer-token-4nnwc istio-envoy sds-uds-path istio-token]
7m43s       Warning   FailedMount   pod/ml-pipeline-6bd8695795-42t4p                       MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
116s        Warning   FailedMount   pod/ml-pipeline-6bd8695795-42t4p                       Unable to mount volumes for pod "ml-pipeline-6bd8695795-42t4p_kubeflow(68d47259-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"ml-pipeline-6bd8695795-42t4p". list of unmounted volumes=[istio-token]. list of unattached volumes=[ml-pipeline-token-tfv8c istio-envoy sds-uds-path istio-token]
7m46s       Warning   FailedMount   pod/ml-pipeline-persistenceagent-55f86769df-ckbjd      MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
3m8s        Warning   FailedMount   pod/ml-pipeline-persistenceagent-55f86769df-ckbjd      Unable to mount volumes for pod "ml-pipeline-persistenceagent-55f86769df-ckbjd_kubeflow(68d94f76-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"ml-pipeline-persistenceagent-55f86769df-ckbjd". list of unmounted volumes=[istio-token]. list of unattached volumes=[ml-pipeline-persistenceagent-token-chsdn istio-envoy sds-uds-path istio-token]
7m43s       Warning   FailedMount   pod/ml-pipeline-scheduledworkflow-669898648c-rjtnd     MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
2m45s       Warning   FailedMount   pod/ml-pipeline-scheduledworkflow-669898648c-rjtnd     Unable to mount volumes for pod "ml-pipeline-scheduledworkflow-669898648c-rjtnd_kubeflow(69620c3b-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"ml-pipeline-scheduledworkflow-669898648c-rjtnd". list of unmounted volumes=[istio-token]. list of unattached volumes=[ml-pipeline-scheduledworkflow-token-kc9qj istio-envoy sds-uds-path istio-token]
7m44s       Warning   FailedMount   pod/ml-pipeline-ui-6d944f5c57-l5rn2                    MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
2m11s       Warning   FailedMount   pod/ml-pipeline-ui-6d944f5c57-l5rn2                    Unable to mount volumes for pod "ml-pipeline-ui-6d944f5c57-l5rn2_kubeflow(6966eadf-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"ml-pipeline-ui-6d944f5c57-l5rn2". list of unmounted volumes=[istio-token]. list of unattached volumes=[config-volume ml-pipeline-ui-token-x8zc4 istio-envoy sds-uds-path istio-token]
97s         Warning   FailedMount   pod/ml-pipeline-viewer-crd-7d4c798d87-dkl42            MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
8m4s        Warning   FailedMount   pod/ml-pipeline-viewer-crd-7d4c798d87-dkl42            Unable to mount volumes for pod "ml-pipeline-viewer-crd-7d4c798d87-dkl42_kubeflow(6970aeec-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"ml-pipeline-viewer-crd-7d4c798d87-dkl42". list of unmounted volumes=[istio-token]. list of unattached volumes=[ml-pipeline-viewer-crd-service-account-token-m9gq9 istio-envoy sds-uds-path istio-token]
7m45s       Warning   FailedMount   pod/ml-pipeline-visualizationserver-7cf6486975-992vc   MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
2m37s       Warning   FailedMount   pod/ml-pipeline-visualizationserver-7cf6486975-992vc   Unable to mount volumes for pod "ml-pipeline-visualizationserver-7cf6486975-992vc_kubeflow(69759073-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"ml-pipeline-visualizationserver-7cf6486975-992vc". list of unmounted volumes=[istio-token]. list of unattached volumes=[ml-pipeline-visualizationserver-token-lwktp istio-envoy sds-uds-path istio-token]
17m         Warning   FailedMount   pod/mysql-7f5ccb5968-bzfkl                             MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
3m13s       Warning   FailedMount   pod/mysql-7f5ccb5968-bzfkl                             Unable to mount volumes for pod "mysql-7f5ccb5968-bzfkl_kubeflow(6a0d1cb4-0158-11eb-aa99-d017c212d537)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"mysql-7f5ccb5968-bzfkl". list of unmounted volumes=[istio-token]. list of unattached volumes=[mysql-persistent-storage default-token-t7jd7 istio-envoy sds-uds-path istio-token]
```

**Comment by jzhoucliqr** [comment]
I guess there is no other way around but to change the apiserver flags. Usually those changes are fine, should not cause issue on existing services, only a couple of seconds downtime for the apiserver to restart.

**Comment by Utkagr** [comment]
Okay. I tried following that and I'm getting the same error mentioned here. https://github.com/kubeflow/manifests/issues/959#issuecomment-682447046 Could you guide me here? I'm not an expert in k8s.

**Comment by Utkagr** [comment]
@jzhoucliqr I was able to fix that issue. Now istio pods are all up. All the pods are running now but my katib-db-manager pod is going CrashloopBackOff; logs say
```
\E0930 09:03:51.026506       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:03:56.028018       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:01.053042       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:06.053409       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:11.053744       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:16.054091       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:21.054478       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:26.054744       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:31.055060       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:36.055307       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:41.055707       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
E0930 09:04:46.055999       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.251.241.169:3306: i/o timeout
F0930 09:04:46.056040       1 main.go:83] Failed to open db connection: DB open failed: Timeout waiting for DB conn successfully opened.
goroutine 1 [running]:
github.com/kubeflow/katib/vendor/k8s.io/klog.stacks(0xc00021c200, 0xc00023a000, 0x89, 0xc2)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:830 +0xb8
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).output(0xdd8580, 0xc000000003, 0xc000234000, 0xd78cae, 0x7, 0x53, 0x0)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:781 +0x2d0
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).printf(0xdd8580, 0x3, 0x992852, 0x20, 0xc0001dbf48, 0x1, 0x1)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:678 +0x14b
github.com/kubeflow/katib/vendor/k8s.io/klog.Fatalf(...)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:1209
main.main()
        /go/src/github.com/kubeflow/katib/cmd/db-manager/v1alpha3/main.go:83 +0x165

```

**Comment by jzhoucliqr** [comment]
can u check if the volume created successfully for katib-mysql ? 
kubectl get pvc -n kubeflow

if the katib-mysql pvc is pending, do a kubectl describe pvc katib-mysql -n kubeflow to see what's the reason why volume cant be created.

**Comment by Utkagr** [comment]
@jzhoucliqr I checked the PVCs. They're all bound. 
```
╰─ kubectl get pvc -n kubeflow
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
katib-mysql      Bound    pvc-b3ff1a2b-02f5-11eb-b9dc-d017c212d537   10Gi       RWO            rook-ceph-block-hdd   42h
metadata-mysql   Bound    pvc-b400a316-02f5-11eb-b9dc-d017c212d537   10Gi       RWO            rook-ceph-block-hdd   42h
minio-pvc        Bound    pvc-b40214bd-02f5-11eb-b9dc-d017c212d537   20Gi       RWO            rook-ceph-block-hdd   42h
mysql-pv-claim   Bound    pvc-b404223b-02f5-11eb-b9dc-d017c212d537   20Gi       RWO            rook-ceph-block-hdd   42h

```

**Comment by jzhoucliqr** [comment]
compared with my setup, this log from katib-mysql pod looks suspicious. I don't see this in my setup. 

2020-09-30T08:22:02.975759Z 0 [ERROR] [MY-011947] [InnoDB] Cannot open '/var/lib/mysql/datadir/ib_buffer_pool' for reading: No such file or directory

**Comment by jbottum** [comment]
Hi @Utkagr , did you get this resolved ?  Note - You might join the Thursday On-Prem SIG calls and discuss with others.

**Comment by Utkagr** [comment]
@jzhoucliqr I checked the describe of katib-sql pod and found this issue https://github.com/kubeflow/katib/issues/1212.
Not sure what the issue is. Could it be related to ceph rdb provider like mentioned here? https://github.com/kubeflow/katib/pull/988#issuecomment-623072410

**Comment by Utkagr** [comment]
> compared with my setup, this log from katib-mysql pod looks suspicious. I don't see this in my setup.
> 
> 2020-09-30T08:22:02.975759Z 0 [ERROR] [MY-011947] [InnoDB] Cannot open '/var/lib/mysql/datadir/ib_buffer_pool' for reading: No such file or directory
> 
> maybe git it a try to restart the pod.

I restarted it. But it's not working.

**Comment by jzhoucliqr** [comment]
> @jzhoucliqr I checked the describe of katib-sql pod and found this [kubeflow/katib#1212](https://github.com/kubeflow/katib/issues/1212). Not sure what the issue is, though. Could it be related to ceph rdb provider like mentioned here? [kubeflow/katib#988 (comment)](https://github.com/kubeflow/katib/pull/988#issuecomment-623072410)

possibly.

**Comment by Utkagr** [comment]
Resolved using https://github.com/kubeflow/katib/issues/1212
