### ISSUE TITLE
not able to run pipeline in kubeflow using kale. 

### ISSUE THREAD

**Issue by JyothsnaPendyala** [kubeflow/manifests#2292]
I am getting the following error when I tried to run pipelines in kubeflow. I have using jupyter kale extension to run pipelines.

022-09-29 05:16:32 Kale mlmdutils:156        [WARNING]  Failed to access the Metadata store. Exception: 'DNS resolution failed'
2022-09-29 05:16:33 Kale mlmdutils:156        [WARNING]  Failed to access the Metadata store. Exception: 'DNS resolution failed'
2022-09-29 05:16:34 Kale mlmdutils:156        [WARNING]  Failed to access the Metadata store. Exception: 'DNS resolution failed'
Traceback (most recent call last):
  File "/tmp/tmp.jO1iliMEi2", line 48, in <module>
    _outputs = load_data(**_parsed_args)
  File "/tmp/tmp.jO1iliMEi2", line 3, in load_data
    _kale_mlmdutils.init_metadata()
  File "/usr/local/lib/python3.6/dist-packages/kale/common/mlmdutils.py", line 537, in init_metadata
    mlmd_instance = MLMetadata()
  File "/usr/local/lib/python3.6/dist-packages/kale/common/mlmdutils.py", line 92, in __init__
    self.store = self._connect()
  File "/usr/local/lib/python3.6/dist-packages/kale/common/mlmdutils.py", line 185, in _connect
    raise RuntimeError("Could not connect to the Metadata store.")
RuntimeError: Could not connect to the Metadata store.

can you please help me with this?

**Comment by juliusvonkohout** [comment]
/close

There has been no activity for a long time. Please reopen if necessary.
