### ISSUE TITLE
How to use nginx ingress controller instead of istio

### ISSUE THREAD

**Issue by Syntax3rror404** [kubeflow/manifests#2407]
I use a rancher cluster build with rke2. I have a fully functional nginx ingress controller. But kubeflow installing by default istio. The DNS server pointing to the nginx ingress with a dns wildcard. I want to expose kubeflow with a nginx ingress as many other applications.

I installed kubeflow 1.6.1

**Comment by Syntax3rror404** [comment]
I added a ingress rule to kubeflow. But i get RBAC: access denied on access

**Comment by Syntax3rror404** [comment]
I now exposed istio over nginx. I dont know if this is the best practise for that. I hope if anyone knows how to deal with kubeflow on a persistent cluster i would be really happy

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["192.168.33.82","192.168.33.83","192.168.33.84"],"port":80,"protocol":"HTTP","serviceName":"istio-system:istio-ingressgateway","ingressName":"istio-system:istio","hostname":"istio.ingress.labza","path":"/","allNodes":false}]
  namespace: istio-system
  resourceVersion: '117082948'
  uid: 149d0de9-56d2-4575-80ca-f3fb76c46c22
  fields:
    - istio
    - <none>
    - istio.ingress.labza
    - 192.168.33.82,192.168.33.83,192.168.33.84
    - '80'
    - 3s
spec:
  rules:
    - host: istio.ingress.labza
      http:
        paths:
          - backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
            path: /
            pathType: Prefix
      vKey: 2011993079
  tls:
  backend:
    {}
cacheObject:
  useNestedBackendField: true
  showPathType: true
__clone: true
```

**Comment by Syntax3rror404** [comment]
But now i cant access the noebook servers. If i click on connect the error upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111 comes up

**Comment by Syntax3rror404** [comment]
Looks like the notebooks server pod cause this problem

```
Traceback (most recent call last):
File "/opt/conda/bin/jupyter-lab", line 8, in <module>
sys.exit(main())
File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 584, in launch_instance
serverapp = cls.initialize_server(argv=args)
File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 554, in initialize_server
serverapp.initialize(
File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 110, in inner
return method(app, *args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2462, in initialize
self.init_configurables()
File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1865, in init_configurables
connection_dir=self.runtime_dir,
File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 686, in __get__
return self.get(obj, cls)
File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 648, in get
default = obj.trait_defaults(self.name)
File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1752, in trait_defaults
return self._get_trait_default_generator(names[0])(self)
File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 106, in _runtime_dir_default
ensure_dir_exists(rd, mode=0o700)
File "/opt/conda/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 12, in ensure_dir_exists
os.makedirs(path, mode=mode)
File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
[I 2023-03-11 21:28:39.149 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2023-03-11 21:28:39.161 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-03-11 21:28:39.161 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2023-03-11 21:28:39.172 ServerApp] nbclassic | extension was successfully linked.
[I 2023-03-11 21:28:39.172 ServerApp] nbdime | extension was successfully linked.
[W 2023-03-11 21:28:39.174 ServerApp] notebook_shim | error linking extension: [Errno 13] Permission denied: '/home/jovyan/.local'
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 645, in get
value = obj._trait_values[self.name]
KeyError: 'browser_open_file'
```

**Comment by juliusvonkohout** [comment]
/close

There has been no activity for a long time. Please reopen if necessary.
