### ISSUE TITLE
metadata-grpc, metadata-writer, mysql pod cannot be ready status

### ISSUE THREAD

**Issue by zengqingfu1442** [kubeflow/manifests#2412]
I also encountered this issue. 
My env:
k8s: 1.19.16
kubeflow manifests: v1.5.1 tag
kustomize: 3.2.0

install command:
```
while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
```

metadata-grpc-deployment-6f6f7776c5-pq6hq log:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0321 09:45:37.213575     1 metadata_store_server_main.cc:236] Check failed: absl::OkStatus() == status (OK vs. INTERNAL: mysql_real_connect failed: errno: , error:  [mysql-error-info='']) MetadataStore cannot be created with the given connection config.
*** Check failure stack trace: ***
```

mysql-f7b9b7dd4-5m4tb logs:
```
2023-03-21 09:47:24+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.33-1debian10 started.
2023-03-21 09:47:27+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
        command was: mysqld --ignore-db-dir=lost+found --datadir /var/lib/mysql --verbose --help --log-bin-index=/tmp/tmp.fbqLrtywDf

```

metadata-writer-d7ff8d4bc-8thjn logs:
```
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 63, in <module>
    mlmd_store = connect_to_mlmd()
  File "/kfp/metadata_writer/metadata_helpers.py", line 62, in connect_to_mlmd
    raise RuntimeError('Could not connect to the Metadata store.')
RuntimeError: Could not connect to the Metadata store.
```

**Comment by annajung** [comment]
This looks like [pipelines](https://github.com/kubeflow/pipelines) related issue and maybe related to https://github.com/kubeflow/pipelines/issues/6121?

Moving the issue to pipelines can make this issue more visible to the right folks.
