### ISSUE TITLE
metadata-grpc-deployment and metadata-writer pods cannot connect mysql, go to CrashLoopBackOff

### ISSUE THREAD

**Issue by yzc1114** [kubeflow/manifests#2471]
/kind bug

### What steps did you take and what happened:

metadata-grpc-deployment log:
```
kubectl logs metadata-grpc-deployment-5c8599b99c-rx8ks -n kubeflow
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0626 09:05:55.970346     1 metadata_store_server_main.cc:231] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0626 09:05:55.970470     1 metadata_store_server_main.cc:232] Retry attempt 0
W0626 09:05:55.977157     1 metadata_store_server_main.cc:231] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0626 09:05:55.977185     1 metadata_store_server_main.cc:232] Retry attempt 1
W0626 09:05:55.984797     1 metadata_store_server_main.cc:231] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0626 09:05:55.984824     1 metadata_store_server_main.cc:232] Retry attempt 2
W0626 09:05:55.992595     1 metadata_store_server_main.cc:231] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0626 09:05:55.992623     1 metadata_store_server_main.cc:232] Retry attempt 3
W0626 09:05:56.000790     1 metadata_store_server_main.cc:231] Connection Aborted with error: ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.
I0626 09:05:56.000814     1 metadata_store_server_main.cc:232] Retry attempt 4
F0626 09:05:56.008821     1 metadata_store_server_main.cc:236] Check failed: absl::OkStatus() == status (OK vs. ABORTED: In the given db, MLMDEnv table exists but no schema_version can be found. This may be due to concurrent connection to the empty database. Please retry connection.) MetadataStore cannot be created with the given connection config.
*** Check failure stack trace: ***

```

metadata-writer log:
```
kubectl logs metadata-writer-6c576c94b8-w5m4f -n kubeflow
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Failed to access the Metadata store. Exception: "no healthy upstream"
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 68, in <module>
    mlmd_store = connect_to_mlmd()
  File "/kfp/metadata_writer/metadata_helpers.py", line 62, in connect_to_mlmd
    raise RuntimeError('Could not connect to the Metadata store.')
RuntimeError: Could not connect to the Metadata store.
```

mysql log:
```
kubectl logs mysql-6878bbff69-6qn6w -n kubeflow
2023-06-26 08:50:01+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.26-1debian10 started.
2023-06-26 08:50:01+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-06-26 08:50:01+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.26-1debian10 started.
2023-06-26 08:50:01+00:00 [Note] [Entrypoint]: Initializing database files
2023-06-26T08:50:01.949846Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.26) initializing of server in progress as process 43
2023-06-26T08:50:02.358511Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-06-26T08:50:48.518736Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-06-26T08:52:26.104230Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1 is enabled for channel mysql_main
2023-06-26T08:52:26.104498Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1.1 is enabled for channel mysql_main
2023-06-26T08:52:26.124958Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2023-06-26 08:55:07+00:00 [Note] [Entrypoint]: Database files initialized
2023-06-26 08:55:07+00:00 [Note] [Entrypoint]: Starting temporary server
2023-06-26T08:55:07.676990Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.26) starting as process 92
2023-06-26T08:55:07.705211Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-06-26T08:55:13.301557Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-06-26T08:55:14.125758Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1 is enabled for channel mysql_main
2023-06-26T08:55:14.126038Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1.1 is enabled for channel mysql_main
2023-06-26T08:55:14.127749Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2023-06-26T08:55:14.128121Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2023-06-26T08:55:14.135225Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2023-06-26T08:55:14.162415Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
2023-06-26T08:55:14.162551Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
2023-06-26 08:55:14+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

2023-06-26 08:55:26+00:00 [Note] [Entrypoint]: Stopping temporary server
2023-06-26T08:55:26.769045Z 10 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.26).
2023-06-26T08:56:22.991820Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.26)  MySQL Community Server - GPL.
2023-06-26 08:56:23+00:00 [Note] [Entrypoint]: Temporary server stopped

2023-06-26 08:56:23+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.

2023-06-26T08:56:23.998454Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.26) starting as process 1
2023-06-26T08:56:24.006667Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-06-26T08:56:28.900296Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-06-26T08:56:30.981970Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1 is enabled for channel mysql_main
2023-06-26T08:56:30.982139Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1.1 is enabled for channel mysql_main
2023-06-26T08:56:30.983162Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2023-06-26T08:56:30.983369Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2023-06-26T08:56:30.992288Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2023-06-26T08:56:31.021636Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2023-06-26T08:56:31.021650Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
```

### Environment:

Metadata version:
metadata grpc deployment docker image: gcr.io/tfx-oss-public/ml_metadata_store_server:1.5.0
Kubeflow version: 1.7.0
Kubernetes version: (use kubectl version): v1.24.4
OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS

**Comment by Interaze** [comment]
Same bug

**Comment by dashanji** [comment]
> Get the same bug:
> 
> ```shell
> $ kubectl get pod -n kubeflow
> NAME                                                     READY   STATUS             RESTARTS         AGE
> admission-webhook-deployment-675d655b55-5ps6x            1/1     Running            0                42m
> cache-server-76cb8f97f9-984zw                            2/2     Running            2 (11m ago)      42m
> centraldashboard-8f568c799-lpq4b                         2/2     Running            0                42m
> jupyter-web-app-deployment-6c4564fd89-42xf6              2/2     Running            0                42m
> katib-controller-86cd58bc95-962w2                        1/1     Running            0                42m
> katib-db-manager-6548966775-cgkdj                        0/1     CrashLoopBackOff   10 (2m57s ago)   42m
> katib-mysql-db6dc68c-5vqgl                               0/1     Running            2 (9m24s ago)    42m
> katib-ui-b48794755-txn9c                                 2/2     Running            1 (36m ago)      42m
> kserve-controller-manager-85b6b6c47d-mwzbf               2/2     Running            0                42m
> kserve-models-web-app-99849d9f7-v9d98                    2/2     Running            0                42m
> kubeflow-pipelines-profile-controller-59ccbd47b9-2gzjj   1/1     Running            0                42m
> metacontroller-0                                         1/1     Running            0                41m
> metadata-envoy-deployment-5b6c575b98-jhzrz               1/1     Running            0                42m
> metadata-grpc-deployment-784b8b5fb4-wcjtv                1/2     CrashLoopBackOff   12 (94s ago)     42m
> metadata-writer-5899c74595-v7gfw                         2/2     Running            9 (6m48s ago)    42m
> minio-65dff76b66-f5mwc                                   2/2     Running            0                42m
> ml-pipeline-7d5658846f-49sxv                             1/2     Running            13 (7s ago)      42m
> ml-pipeline-persistenceagent-798dbf666f-j8d7j            2/2     Running            0                42m
> ml-pipeline-scheduledworkflow-859ff9cf7b-dhjf7           2/2     Running            0                42m
> ml-pipeline-ui-6d69549787-svwkc                          2/2     Running            0                42m
> ml-pipeline-viewer-crd-56f7cfd7d9-sv256                  2/2     Running            1 (35m ago)      42m
> ml-pipeline-visualizationserver-64447ffc76-gvk69         2/2     Running            0                42m
> mysql-c999c6c8-4bvnw                                     1/2     CrashLoopBackOff   11 (4m35s ago)   42m
> notebook-controller-deployment-5d976f4d6-6mjbq           2/2     Running            1 (34m ago)      42m
> profiles-deployment-5d76d4dd84-qgtfm                     3/3     Running            1 (33m ago)      42m
> tensorboard-controller-deployment-79ddb58cf-88lp6        3/3     Running            1 (34m ago)      42m
> tensorboards-web-app-deployment-c4698556b-8v4m5          2/2     Running            0                42m
> training-operator-d8799bf5c-n5swr                        1/1     Running            0                42m
> volumes-web-app-deployment-76c989f44c-k9lw5              2/2     Running            0                42m
> workflow-controller-6547f784cd-9f74r                     2/2     Running            1 (39m ago)      42m
> ```
> 
> katib-db-manager log:
> 
> ```shell
> I0728 08:01:48.256308       1 db.go:32] Using MySQL
> E0728 08:01:54.290707       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:01:59.282717       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:04.278787       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:09.270718       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:14.290723       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:19.282767       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:24.274714       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:29.266729       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:34.290715       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:39.286714       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:44.274709       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> E0728 08:02:49.266715       1 connection.go:40] Ping to Katib db failed: dial tcp 10.96.36.68:3306: connect: connection refused
> F0728 08:02:49.266748       1 main.go:104] Failed to open db connection: DB open failed: Timeout waiting for DB conn successfully opened.
> ```
> 
> metadata-grpc-deployment log:
> 
> ```shell
> Check failed: absl::OkStatus() == status (OK vs. INTERNAL: mysql_real_connect failed: errno:  , error:  [mysql-error-info='']) MetadataStore cannot be created with the given connection config.
> ```
> 
> mysql log:
> 
> ```shell
>  2023-07-28 08:01:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.26-1debian10 started.   │
> │ 2023-07-28 08:01:11+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config                │
> │     command was: mysqld --datadir /var/lib/mysql --default-authentication-plugin=mysql_native_password --disa │
> │     mysqld: Can't read dir of '/etc/mysql/conf.d/' (OS errno 13 - Permission denied)                          │
> │ mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
> ```

I use the kind to create a kubernetes cluster and then deploy the manifests, actually the bug is caused by [AppArmor](https://docs.docker.com/engine/security/apparmor/). If anyone is faced with this question, you could refer the [doc](https://linuxconfig.org/how-to-disable-apparmor-on-ubuntu-20-04-focal-fossa-linux) on how to disable the AppArmor.

**Comment by LiaoSirui** [comment]
Get the same bug

metadata-grpc-deployment with no log

**Comment by LiaoSirui** [comment]
it may help. 

patch mysql using:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      metadata:
        labels:
          app: mysql
          sidecar.istio.io/inject: "false"
```

reffer: https://istio.io/latest/zh/about/faq/security/#mysql-with-mtls

**Comment by manang** [comment]
did you solve this issue? thanks

**Comment by nick0323** [comment]
has anyone solved this problem?

**Comment by LiaoSirui** [comment]
> it may help.
> 
> patch mysql using:
> 
> ```yaml
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: mysql
> spec:
>   template:
>     spec:
>       metadata:
>         labels:
>           app: mysql
>           sidecar.istio.io/inject: "false"
> ```
> 
> reffer: https://istio.io/latest/zh/about/faq/security/#mysql-with-mtls

@nick0323 @manang  maybe caused by istio destinationrule, just delete it, then success( but it works on my another machine)

**Comment by nick0323** [comment]
> > it may help.
> > patch mysql using:
> > ```yaml
> > apiVersion: apps/v1
> > kind: Deployment
> > metadata:
> >   name: mysql
> > spec:
> >   template:
> >     spec:
> >       metadata:
> >         labels:
> >           app: mysql
> >           sidecar.istio.io/inject: "false"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > reffer: https://istio.io/latest/zh/about/faq/security/#mysql-with-mtls
> 
> @nick0323 @manang maybe caused by istio destinationrule, just delete it, then success( but it works on my another machine)
Solved this problem by insert schema_version to mysql, sql:  use metadb, insert into MLMDEnv values ("7"); ml-metadata 1.5.0  schema_version is 7 for me, detail schema_version  https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md, then restart metadata-grpc-deployment pod.

**Comment by 453875726** [comment]
> > it may help.
> > patch mysql using:
> > ```yaml
> > apiVersion: apps/v1
> > kind: Deployment
> > metadata:
> >   name: mysql
> > spec:
> >   template:
> >     spec:
> >       metadata:
> >         labels:
> >           app: mysql
> >           sidecar.istio.io/inject: "false"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > reffer: https://istio.io/latest/zh/about/faq/security/#mysql-with-mtls
> 
> @nick0323 @manang maybe caused by istio destinationrule, just delete it, then success( but it works on my another machine)

您好，请问在哪修改这个文件？还是将这段内容加入到一个yaml文件中？

**Comment by LiaoSirui** [comment]
> > > it may help.
> > > patch mysql using:
> > > ```yaml
> > > apiVersion: apps/v1
> > > kind: Deployment
> > > metadata:
> > >   name: mysql
> > > spec:
> > >   template:
> > >     spec:
> > >       metadata:
> > >         labels:
> > >           app: mysql
> > >           sidecar.istio.io/inject: "false"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > reffer: https://istio.io/latest/zh/about/faq/security/#mysql-with-mtls
> > 
> > 
> > @nick0323 @manang maybe caused by istio destinationrule, just delete it, then success( but it works on my another machine)
> 
> 您好，请问在哪修改这个文件？还是将这段内容加入到一个yaml文件中？

不是，改下 mysql 的 label ，禁止 istio 注入，从而防止 mTLS 影响 MySQL

**Comment by manang** [comment]
sorry, can you write the rite yaml configuration file?

**Comment by LiaoSirui** [comment]
> sorry, can you write the rite yaml configuration file?

it's a patch yaml (kustomization.yaml -> patchesStrategicMerge)

**Comment by 453875726** [comment]
> > > > it may help.
> > > > patch mysql using:
> > > > ```yaml
> > > > apiVersion: apps/v1
> > > > kind: Deployment
> > > > metadata:
> > > >   name: mysql
> > > > spec:
> > > >   template:
> > > >     spec:
> > > >       metadata:
> > > >         labels:
> > > >           app: mysql
> > > >           sidecar.istio.io/inject: "false"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > reffer: https://istio.io/latest/zh/about/faq/security/#mysql-with-mtls
> > > 
> > > 
> > > @nick0323 @manang maybe caused by istio destinationrule, just delete it, then success( but it works on my another machine)
> > 
> > 
> > 您好，请问在哪修改这个文件？还是将这段内容加入到一个yaml文件中？
> 
> 不是，改下 mysql 的 label ，禁止 istio 注入，从而防止 mTLS 影响 MySQL

谢谢，我发现我的问题是由于缺少mysql镜像，下载后已解决

**Comment by juliusvonkohout** [comment]
Please retest with a vanilla Kubeflow 1.8

"sidecar.istio.io/inject: "false"" is very dangerous advice.

**Comment by shaejaz** [comment]
Was facing the same issue with a [deploykf](https://www.deploykf.org/) install during the ArgoCD sync resources stage. I resolved it by deleting the mysql `StatfulSet`, the attached `PV` and `PVC` and then rerunning the sync script. The cluster seems to be working ok after the `ml-pipelines` deployment was restarted. I'd assume any other component requiring the mysql db would need restarts as well.

**Comment by thesuperzapper** [comment]
> Was facing the same issue with a [deploykf](https://www.deploykf.org/) install during the ArgoCD sync resources stage. I resolved it by deleting the mysql `StatfulSet`, the attached `PV` and `PVC` and then rerunning the sync script. The cluster seems to be working ok after the `ml-pipelines` deployment was restarted. I'd assume any other component requiring the mysql db would need restarts as well.

@shaejaz I am very interested if you can reproduce that error. If you can, could you raise an issue on the deployKF repo so we can get it fixed?

Also, just for some context, could you clarify what kind of Kubernetes you are using? (e.g. a local k3d cluster or a cloud vendor like EKS)

**Comment by shaejaz** [comment]
@thesuperzapper Honestly, I think it was most likely due to my ssh connection being dropped mid install and the cluster being left in a weird state. I just gave some tips on the quickest way to re-install just the mysql component without going through the entire lengthy full install again.

I'm using a single node k3s cluster. It's not installed via k3d though, that just errors out at the ArgoCD sync step for me (not sure why that happens)

**Comment by thesuperzapper** [comment]
> @thesuperzapper Honestly, I think it was most likely due to my ssh connection being dropped mid install and the cluster being left in a weird state. I just gave some tips on the quickest way to re-install just the mysql component without going through the entire lengthy full install again.
> 
> I'm using a single node k3s cluster. It's not installed via k3d though, that just errors out at the ArgoCD sync step for me (not sure why that happens)

@shaejaz can you raise an issue that shows your `k3d` ArgoCD sync error on the [deployKF issue tracker](https://github.com/deployKF/deployKF)?

I use k3d with deployKF all the time and it works perfectly, so I wonder if we will uncover an issue specific to your environment.

Also, are you using a MacOS or Linux?

**Comment by teocns** [comment]
I faced the same issue across different versions of kubeflow / kuberneetes; annotating `mysql` deployment with `sidecar.istio.io/inject: "false"` has solved the issue for me too.

> @juliusvonkohout  "sidecar.istio.io/inject: "false"" is very dangerous advice.

Could you define "dangerous"?
