### ISSUE TITLE
ml-pipeline api server crashes - missing flag MYSQL_SERVICE_HOST

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/manifests#98]
```
I0521 20:31:07.780074       8 client_manager.go:119] Initializing client manager
F0521 20:31:07.780842       8 config.go:47] Please specify flag MYSQL_SERVICE_HOST
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc0002b6a00, 0xc000588c80, 0x53, 0x9b)
        external/com_github_golang_glog/glog.go:769 +0xd4
github.com/golang/glog.(*loggingT).output(0x2957260, 0xc000000003, 0xc00001cfd0, 0x2837d77, 0x9, 0x2f, 0x0)
        external/com_github_golang_glog/glog.go:720 +0x329
github.com/golang/glog.(*loggingT).printf(0x2957260, 0xc000000003, 0x1a91814, 0x16, 0xc0005419e0, 0x1, 0x1)
        external/com_github_golang_glog/glog.go:655 +0x14b
github.com/golang/glog.Fatalf(0x1a91814, 0x16, 0xc0005419e0, 0x1, 0x1)
        external/com_github_golang_glog/glog.go:1148 +0x67
main.getStringConfig(0x1a8c161, 0x12, 0x1a8d4d9, 0x13)
        backend/src/apiserver/config.go:47 +0xf8
main.initMysql(0xc00032943a, 0x5, 0x53d1ac1000, 0x0, 0x0)
        backend/src/apiserver/client_manager.go:222 +0x53
main.initDBClient(0x53d1ac1000, 0x15)
        backend/src/apiserver/client_manager.go:185 +0x5c0
main.(*ClientManager).init(0xc000541cd8)
        backend/src/apiserver/client_manager.go:121 +0x80
main.newClientManager(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        backend/src/apiserver/client_manager.go:292 +0x7b
main.main()
        backend/src/apiserver/main.go:56 +0x5e
```

**Comment by gabrielwen** [comment]
@IronPan could you give me some pointers how `MYSQL_SERVICE_HOST` is set currently?  Somehow api-server doesn't have this ENV when deploying with kustomize.

**Comment by gabrielwen** [comment]
turns out it's most likely naming issue.
